# Admin
/admin/account/update/{id}:
    controller: 'AdminController'
    action: 'update_admin_account'
    role: 'admin'
    

# Clients
/admin/client/delete/{id}:
  controller: 'ClientController'
  action: 'delete'

# Ajax 
/admin/ajax/delete/{id}:
  controller: 'AjaxController' 
  action: 'delete'

/admin/page/edit/{id}:
  controller: 'PostController'
  action: 'edit_page'

/admin/page/delete/{id}:
  controller: 'PostController'
  action: 'delete_page'

# Product 
/admin/product/update/{id}:
  controller: "ProductController"
  action: "update_product"

/admin/product/delete/{id}:
  controller: "ProductController"
  action: "delete_product"

/admin/menu/edit/{id}:
  controller: 'MenuController'
  action: 'edit_link'

/product/{id}:
  controller: 'ProductController'
  action: 'product'

/admin/type/delete/{id}: 
  controller: "ProductController"
  action: "delete_product_type"

# Affichage des pages
/{slug}:
  controller: "PostController"
  action: "show_page"