/admin/page/edit/{slug}:
  controller: 'PostController'
  action: 'edit_page'

# Clients
/admin/client/delete/{id}:
  controller: 'ClientController'
  action: 'delete'

# Ajax 
/admin/ajax/delete/client/{id}:
  controller: 'AjaxController' 
  action: 'delete_client'