/admin/page/edit/{slug}:
  controller: 'PostController'
  action: 'edit_page'

# Clients
/admin/client/delete/{id}:
  controller: 'ClientController'
  action: 'delete'

# Ajax 
/admin/ajax/delete/{id}:
  controller: 'AjaxController' 
  action: 'delete'

/admin/page/edit/{id}:
  controller: 'PostController'
  action: 'edit_page'

/admin/page/delete/{id}:
  controller: 'PostController'
  action: 'delete_page'

# Product 
/admin/product/update/{id}:
  controller: "ProductController"
  action: "update_product"

/admin/product/delete/{id}:
  controller: "ProductController"
  action: "delete_product"
