/admin/page/edit/{slug}:
  controller: 'PostController'
  action: 'edit_page'

/admin/page/edit/{id}:
  controller: 'PostController'
  action: 'edit_page'

/admin/page/delete/{id}:
  controller: 'PostController'
  action: 'delete_page'

/admin/product/update/{id}:
  controller: "ProductController"
  action: "update_product"