/login:
  controller: "SecurityController"
  action: "login"

/register:
  controller: "SecurityController"
  action: "register"

/cart:
    controller: "CartController"
    action: "confirm_order"

/product:
  controller: "ProductController"
  action: "register_product"
