/login:
  controller: "Security"
  action: "login"

/register:
  controller: "Security"
  action: "register"

/cart:
    controller: "CartController"
    action: "confirm_order"

/form-product:
  controller: "ProductController"
  action: "add_product"

/dashboard:
    controller: "DashboardController"
    action: "dashboard"

/form-create-email-template:
    controller: 'EmailController'
    action: 'setTemplate'
  
/all_users:
    controller: 'UserController'
    action: 'all_users'

/all_accounts:
    controller: 'AdminController'
    action: 'all_accounts'