/login:
  controller: "SecurityController"
  action: "login"

/register:
  controller: "SecurityController"
  action: "register"

/product:
  controller: "ProductController"
  action: "register_product"
