/login:
  controller: "SecurityController"
  action: "login"

/register:
  controller: "SecurityController"
  action: "register"

/cart:
    controller: "CartController"
    action: "confirm_order"

/admin/product/create:
  controller: "ProductController"
  action: "add_product"

/admin/type/create: 
  controller: "ProductController"
  action: "add_type"

/dashboard:
    controller: "DashboardController"
    action: "dashboard"

/form-create-email-template:
    controller: 'EmailController'
    action: 'setTemplate'
  
/admin/clients:
    controller: 'ClientController'
    action: 'all_clients'

/admin/accounts:
    controller: 'AdminController'
    action: 'all_admin_accounts'

/admin/account/create:
    controller: 'AdminController'
    action: 'add_admin_account'

/404:
  controller: 'SecurityController'
  action: 'not_found'

/admin/products:
    controller: 'ProductController'
    action: 'get_all_products'
