/login:
  controller: "SecurityController"
  action: "login"

/register:
  controller: "SecurityController"
  action: "register"

/cart:
    controller: "CartController"
    action: "confirm_order"

/form-product:
  controller: "ProductController"
  action: "add_product"

/dashboard:
    controller: "DashboardController"
    action: "dashboard"

/form-create-email-template:
    controller: 'EmailController'
    action: 'setTemplate'
  
/admin/clients:
    controller: 'ClientController'
    action: 'all_clients'

/admin/accounts:
    controller: 'AdminController'
    action: 'all_admin_accounts'

/admin/account/create:
    controller: 'AdminController'
    action: 'add_admin_account'

/admin/page/add:
  controller: 'PostController'
  action: 'add_page'

/admin/pages:
  controller: 'PostController'
  action: 'all_pages'