/login:
  controller: "Security"
  action: "login"

/register:
  controller: "Security"
  action: "register"

/cart:
    controller: "CartController"
    action: "confirm_order"

/dashboard:
    controller: "Dashboard"
    action: "dashboard"