/:
  controller: "PostController"
  action: "show_home"

# Security
/login:
  controller: "SecurityController"
  action: "login"

/logout:
  controller: "SecurityController"
  action: "logout"

/register:
  controller: "SecurityController"
  action: "register"

/404:
  controller: 'SecurityController'
  action: 'not_found'

/forbidden:
  controller: 'SecurityController'
  action: 'forbidden'

/admin/login:
  controller: "SecurityController"
  action: "admin_login"

# Admin

/admin/accounts:
    controller: 'AdminController'
    action: 'all_admin_accounts'
    role: 'admin'

/admin/account/create:
    controller: 'AdminController'
    action: 'add_admin_account'
    role: 'admin'

# Cart     
/cart:
    controller: "CartController"
    action: "confirm_order"
  
# Dashboard
/admin:
    controller: "DashboardController"
    action: "dashboard"
    role: 'admin'

# Email    
/add_email_template:
    controller: 'EmailController'
    action: 'setTemplate'

# Client    
/admin/clients:
    controller: 'ClientController'
    action: 'all_clients'
    role: 'admin'

#Media
/admin/media:
  controller: 'MediaController'
  action: 'all_media'

/admin/media/add-media:
  controller: 'MediaController'
  action: 'add_media'


# Product
/admin/type/create: 
  controller: "ProductController"
  action: "add_product_type"
  role: 'admin'

/admin/product/create:
  controller: "ProductController"
  action: "add_product"
  role: 'admin'

/admin/products:
  controller: 'ProductController'
  action: 'all_products'
  role: 'admin'

/shop:
  controller: 'ProductController'
  action: 'shop'
  
# Ajax
/admin/ajax/open_modal:
  controller: 'AjaxController'
  action: 'open_modal'
  role: 'admin'

# Page
/admin/page/add:
  controller: 'PostController'
  action: 'add_page'
  role: 'admin'

/admin/pages:
  controller: 'PostController'
  action: 'all_pages'
  role: 'admin'

# Menu
/admin/menu:
  controller: 'MenuController'
  action: 'show_menu'
  role: 'admin'

/admin/menu/add:
  controller: 'MenuController'
  action: 'add_link'
  role: 'admin'
  
# Settings
/admin/settings:
  controller: 'DashboardController'
  action: 'settings'
  
# Tuto
/admin/tuto:
  controller: 'TutoController'
  action: 'show_tuto'
  role: 'admin'
