# Security
/login:
  controller: "SecurityController"
  action: "login"

/register:
  controller: "SecurityController"
  action: "register"

/404:
  controller: 'SecurityController'
  action: 'not_found'

# Admin 

/admin/accounts:
    controller: 'AdminController'
    action: 'all_admin_accounts'

/admin/account/create:
    controller: 'AdminController'
    action: 'add_admin_account'

# Cart     
/cart:
    controller: "CartController"
    action: "confirm_order"
  
# Dashboard
/dashboard:
    controller: "DashboardController"
    action: "dashboard"

# Email    
/add_email_template:
    controller: 'EmailController'
    action: 'setTemplate'

# Client    
/admin/clients:
    controller: 'ClientController'
    action: 'all_clients'


# Product
/admin/products:
    controller: 'ProductController'
    action: 'all_products'

/404:
  controller: 'SecurityController'
  action: 'not_found'

# Ajax
/admin/ajax/open_modal:
  controller: 'AjaxController'
  action: 'open_modal'
/admin/product/create:
  controller: "ProductController"
  action: "add_product"

/admin/type/create: 
  controller: "ProductController"
  action: "add_product_type"


# Page
/admin/page/add:
  controller: 'PostController'
  action: 'add_page'

/admin/pages:
  controller: 'PostController'
  action: 'all_pages'
